name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc cmake ninja-build

    - name: Configure project
      run: |
        ./source/scripts/configure.sh release

    - name: Build project
      run: |
        ./source/scripts/build.sh release

    - name: Run tests
      run: |
        ./source/scripts/test.sh release
